# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eresponse.proto\"\x92\x04\n\x0bVSPResponse\x12\n\n\x02\x66\x31\x18\x01 \x01(\x07\x12\n\n\x02\x66\x32\x18\x02 \x01(\t\x12\x17\n\x02\x66\x33\x18\x03 \x01(\x0b\x32\x0b.Msg_15b6f0\x12\x17\n\x02\x66\x34\x18\x04 \x01(\x0b\x32\x0b.Msg_15b6c0\x12\x17\n\x02\x66\x35\x18\x05 \x01(\x0b\x32\x0b.Msg_15b690\x12\x17\n\x02\x66\x36\x18\x06 \x01(\x0b\x32\x0b.Msg_15b660\x12\x17\n\x02\x66\x37\x18\x07 \x01(\x0b\x32\x0b.Msg_15b630\x12\x17\n\x02\x66\x38\x18\x08 \x01(\x0b\x32\x0b.Msg_15b5f0\x12\x17\n\x02\x66\x39\x18\t \x01(\x0b\x32\x0b.Msg_15b5b0\x12\x18\n\x03\x66\x31\x30\x18\n \x01(\x0b\x32\x0b.Msg_15b570\x12\x18\n\x03\x66\x31\x31\x18\x0b \x01(\x0b\x32\x0b.Msg_15b530\x12\x18\n\x03\x66\x31\x32\x18\x0c \x01(\x0b\x32\x0b.Msg_15b500\x12\x18\n\x03\x66\x31\x33\x18\r \x01(\x0b\x32\x0b.Msg_15b4d0\x12\x18\n\x03\x66\x31\x34\x18\x0e \x01(\x0b\x32\x0b.Msg_15b4a0\x12\x18\n\x03\x66\x31\x35\x18\x0f \x01(\x0b\x32\x0b.Msg_15b470\x12\x19\n\x04\x66\x31\x30\x30\x18\x64 \x01(\x0b\x32\x0b.Msg_15b420\x12\x19\n\x04\x66\x31\x30\x31\x18\x65 \x01(\x0b\x32\x0b.Msg_15b3f0\x12\x19\n\x04\x66\x31\x30\x32\x18\x66 \x01(\x0b\x32\x0b.Msg_15b3c0\x12\x19\n\x04\x66\x31\x30\x33\x18g \x01(\x0b\x32\x0b.Msg_15b390\x12\x19\n\x04\x66\x31\x30\x34\x18h \x01(\x0b\x32\x0b.Msg_15b360\x12\x19\n\x04\x66\x31\x30\x35\x18i \x01(\x0b\x32\x0b.Msg_15b320\"\x18\n\nMsg_15b6f0\x12\n\n\x02\x66\x31\x18\x01 \x02(\x05\"\x0c\n\nMsg_15b6c0\"\x0c\n\nMsg_15b690\"\x0c\n\nMsg_15b660\"\x18\n\nMsg_15b630\x12\n\n\x02\x66\x31\x18\x01 \x02(\x05\"\x0c\n\nMsg_15b5f0\"\x18\n\nMsg_15b5b0\x12\n\n\x02\x66\x31\x18\x01 \x02(\x05\"\x0c\n\nMsg_15b570\"\x0c\n\nMsg_15b530\"\x0c\n\nMsg_15b500\"\x0c\n\nMsg_15b4d0\"\x0c\n\nMsg_15b4a0\"\x0c\n\nMsg_15b470\"\x18\n\nMsg_15b420\x12\n\n\x02\x66\x31\x18\x01 \x01(\x05\"\x0c\n\nMsg_15b3f0\"\x18\n\nMsg_15b3c0\x12\n\n\x02\x66\x31\x18\x01 \x01(\t\"\x0c\n\nMsg_15b390\"\x0c\n\nMsg_15b360\"\x0c\n\nMsg_15b320')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'response_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VSPRESPONSE']._serialized_start=19
  _globals['_VSPRESPONSE']._serialized_end=549
  _globals['_MSG_15B6F0']._serialized_start=551
  _globals['_MSG_15B6F0']._serialized_end=575
  _globals['_MSG_15B6C0']._serialized_start=577
  _globals['_MSG_15B6C0']._serialized_end=589
  _globals['_MSG_15B690']._serialized_start=591
  _globals['_MSG_15B690']._serialized_end=603
  _globals['_MSG_15B660']._serialized_start=605
  _globals['_MSG_15B660']._serialized_end=617
  _globals['_MSG_15B630']._serialized_start=619
  _globals['_MSG_15B630']._serialized_end=643
  _globals['_MSG_15B5F0']._serialized_start=645
  _globals['_MSG_15B5F0']._serialized_end=657
  _globals['_MSG_15B5B0']._serialized_start=659
  _globals['_MSG_15B5B0']._serialized_end=683
  _globals['_MSG_15B570']._serialized_start=685
  _globals['_MSG_15B570']._serialized_end=697
  _globals['_MSG_15B530']._serialized_start=699
  _globals['_MSG_15B530']._serialized_end=711
  _globals['_MSG_15B500']._serialized_start=713
  _globals['_MSG_15B500']._serialized_end=725
  _globals['_MSG_15B4D0']._serialized_start=727
  _globals['_MSG_15B4D0']._serialized_end=739
  _globals['_MSG_15B4A0']._serialized_start=741
  _globals['_MSG_15B4A0']._serialized_end=753
  _globals['_MSG_15B470']._serialized_start=755
  _globals['_MSG_15B470']._serialized_end=767
  _globals['_MSG_15B420']._serialized_start=769
  _globals['_MSG_15B420']._serialized_end=793
  _globals['_MSG_15B3F0']._serialized_start=795
  _globals['_MSG_15B3F0']._serialized_end=807
  _globals['_MSG_15B3C0']._serialized_start=809
  _globals['_MSG_15B3C0']._serialized_end=833
  _globals['_MSG_15B390']._serialized_start=835
  _globals['_MSG_15B390']._serialized_end=847
  _globals['_MSG_15B360']._serialized_start=849
  _globals['_MSG_15B360']._serialized_end=861
  _globals['_MSG_15B320']._serialized_start=863
  _globals['_MSG_15B320']._serialized_end=875
# @@protoc_insertion_point(module_scope)
